### ISSUE TITLE
Add set cardinality etimation

### ISSUE THREAD

**Issue by t0k4rt** [yankun1992/fastbloom#12]
Hello, 

I want to implement a set cardinality estimation function
I'm working on a PR (#11) but I cannot manage to launch my unit tests.
Do you have any advice on how to  build the project and launch the rust and python test suite ?

I installed maturin, launched `maturin develop --release` 
then tried to launch the unit tests with `python -m unittest py_tests.test_bloom.test_bloom_add`
but the test fails.

Thanks for your advices

**Comment by yankun1992** [comment]
Hi,
Thanks for your contribution, this project's github action ymal profile may be able to help you.

------------------ Original ------------------
From: Alexandre Assouad ***@***.***&gt;
Date: Wed,Oct 4,2023 9:41 PM
To: yankun1992/fastbloom ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [yankun1992/fastbloom] Add set cardinality etimation (Issue #12)





 
Hello,
 
I want to implement a set cardinality estimation function
 I'm working on a PR (#11) but I cannot manage to launch my unit tests.
 Do you have any advice on how to  build the project and launch the rust and python test suite ?
 
I installed maturin, launched maturin develop --release
 then tried to launch the unit tests with python -m unittest py_tests.test_bloom.test_bloom_add
 but the test fails.
 
Thanks for your advices

**Comment by t0k4rt** [comment]
Hi, thanks for the tip !
The PR is working as expected with the added unit tests

**Comment by yankun1992** [comment]
Hi,
Thanks again for your contribution, but unfortunately I'm on vacation today and I can't deal with this PR until about 2 days later.


------------------ Original ------------------
From: Alexandre Assouad ***@***.***&gt;
Date: Wed,Oct 4,2023 10:33 PM
To: yankun1992/fastbloom ***@***.***&gt;
Cc: Yan Kun ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [yankun1992/fastbloom] Add set cardinality etimation (Issue #12)





 
Hi, thanks for the tip !
 The PR is working as expected with the added unit tests

**Comment by t0k4rt** [comment]
No problems,
Have a nice vacation !

**Comment by yankun1992** [comment]
Published 0.5.7
