### ISSUE TITLE
Load from file (wsl, Python)

### ISSUE THREAD

**Issue by ken2709** [yankun1992/fastbloom#13]
Hi Yankun,

I testing load from file test.bin created with 10bil items, test.bin with 11.7Gb it load to Ram but need 23.4Gb Ram to load. My pc 16Gb ram and it load swap after loaded (224 second), 6Gb in real Ram and 6Gb in swap and bloomfilter it progress slow.
So it need double ram with .bin file to load and progress quickly ?

Thanks,

**Comment by yankun1992** [comment]
Does you release the `bytes` object in Python after you buid a new bloom filter? When you create a new bloom filter from `bytes`, it copy the bits data to the new bloom filter, so you can release the bytes obect after created.

**Comment by ken2709** [comment]
> Does you release the `bytes` object in Python after you buid a new bloom filter? When you create a new bloom filter from `bytes`, it copy the bits data to the new bloom filter, so you can release the bytes obect after created.

I am not sure understand your mean. Could you please give example code ?
I also try with bloom.add(test) problem the same.

This is code create:
bloom = BloomFilter(line_count, 0.0001)
bloom.add_bytes(test)
with open(file_bin, "wb") as f:
     array = bloom.get_bytes()
     f.write(array)

This is for query:
with open(file_pybf, "rb") as fp:
    bloom = BloomFilter.from_bytes(fp.read(), 7)
if bloom.contains_bytes(test):
   print(f" Found: {test.hex()}")

Thanks.

**Comment by yankun1992** [comment]
It looks like there's a need to add an API for building Bloom filters directly from files; the existing API involves multiple memory copies, which is not very memory efficient in a very large Bloom filter.

**Comment by ken2709** [comment]
Hi @yankun1992 

Now it ok, it faster than pybloom 2.5x not 10x don't know where i am missing for case above.

Thank you.

**Comment by yankun1992** [comment]
My guess is cpu cache miss，i am not sure. Can you try the batch API ?

**Comment by ken2709** [comment]
Yes, i try with the batch 105.600k query.

**Comment by yankun1992** [comment]
Can you show me some code?

**Comment by ken2709** [comment]
> Can you show me some code?

Here below code for query I tested, 105600000 items Pub run without bloom 5.5s, run with bloom take 31s.

Query (Multiprocessing 8 thread):
    bloom = BloomFilter.from_file_with_hashes('bloom_test.bin')
    st = time()
    for _ in range(start, end): 
        tpub = bytes(bytearray(point_addition(step_up, pubadd)))
        Pub = pubadd[1:33] 
        if bloom.contains(Pub): 
            print(f" Found: {Pub.hex()}")
            
    print('[-] Completed in {0:.2f} sec'.format(time() - st))
