### ISSUE TITLE
Would it be possible to have add_if_not_contains?

### ISSUE THREAD

**Issue by craigschmidt** [yankun1992/fastbloom#6]
Your library looks great. My use case is in deduplication, so I would be wanting to know if a given string is already in the Bloom filter, and add it if not.  I can certainly make a call to `contains`, and then a call to `add_str`, but it seems like that will be repeating computing all the hash values.  I assume it would run roughly twice as slow as a combined function could.  Would that be something that would be possible to add? It would return whether it was added or not.   Thanks!

**Comment by yankun1992** [comment]
Hi @craigschmidt , sorry for not noticing this issue. I submitted some code to implement the `add_if_not_contains` method, do you see that it meets your needs?

**Comment by yankun1992** [comment]
Release version 0.5.4. Closed.
